/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_nask_hsn_ngrams_NGramsCalc */

#ifndef _Included_pl_nask_hsn_ngrams_NGramsCalc
#define _Included_pl_nask_hsn_ngrams_NGramsCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_nask_hsn_ngrams_NGramsCalc
 * Method:    calcNgrams
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pl_nask_hsn2_service_analysis_NGramsCalc_calcNgrams
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
